# Stage 1: Build ASP.NET API
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS backend-builder
WORKDIR /src
COPY ./src/API/LMS_API/ ./API/LMS_API/
RUN dotnet restore "./API/LMS_API/LMS_API.csproj"
COPY . .
RUN dotnet publish "./API/LMS_API/LMS_API.csproj" -c Release -o /app/publish

# Stage 2: Build Angular Frontend
FROM node:18 AS frontend-builder
WORKDIR /app/frontend
COPY ./src/Front-end-web/ .
RUN npm install
RUN npm run build -- --configuration production

# Stage 3: Serve API and Frontend
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=backend-builder /app/publish ./API
COPY --from=frontend-builder /app/frontend/dist/browser ./wwwroot

# Expose ports for API and frontend
EXPOSE 7030 80
  
# EXPOSE 80   # Nginx (for Angular frontend)
# EXPOSE 7030 # ASP.NET API

# Start API and serve frontend
ENTRYPOINT ["dotnet", "API/LMS_API.dll"]

 
