version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: DockerFile
      target: backend-builder  # Use the backend build stage
    ports:
      - "7070:7030"  # Map local 7030 to container's port 7030 for API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network 
      
    healthcheck:  # Healthcheck added here
      test: ["CMD", "curl", "-f", "http://localhost:80"]  # Command to check service health
      interval: 30s        # Time between health checks
      timeout: 10s         # Time before failing a health check
      retries: 3           # Number of retries before marking as unhealthy


  frontend:
    build:
      context: .
      dockerfile: DockerFile
      target: frontend-builder  # Use the frontend build stage
    ports:
      - "8080:4200"  # Map local 8080 to container's port 4200 for Angular frontend
    networks:
      - app-network
    depends_on:
      - api
      
    healthcheck:  # Healthcheck for the frontend service
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
     

