version: '3'

services:
  api:
    build:
      context: .
      dockerfile: DockerFile
      target: backend-builder  # Use the backend build stage
    ports:
      - "7070:7030"  # Map local 7030 to container's port 7030 for API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: DockerFile
      target: frontend-builder  # Use the frontend build stage
    ports:
      - "8080:4200"  # Map local 8080 to container's port 4200 for Angular frontend
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
    
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:8080"]
  interval: 30s
  timeout: 10s
  retries: 3

