version: '3'

services:
  api:
    build:
      context: .
      dockerfile: DockerFile
      target: backend-builder  # Use the backend build stage
    ports:
      - "7070:80"  # Map local 7031 to container's port 80 for API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: DockerFile
      target: frontend-builder  # Use the frontend build stage
    ports:
      - "8080:80"  # Map local 8080 to container's port 80 for Angular frontend
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
