export class LedgerRequestViewModel {
  accLedgersTempId: number;
  creaditAccLedgerName: string;
  creaditLedgerId: number;
  creaditSubLedgerId: number | null;
  debitAccLedgerName: string;
  debitLedgerId: number;
  debitSubLedgerId: number | null;
  amount: number;
  balance: number | null;
  narration: string;
  creaditLedgerCode: string;
  creaditSubLedgerCode: string;
  debitLedgerCode: string;
  debitSubLedgerCode: string;
  voucherNumber: string;
  voucherType: string;
  status: string;
  createdDate: string;
  creaditUniqId: number | null;
  debitUniqId: number | null;
  supplierCostingHeadId: number;
  partyId: number;
  purchaseOrderId: number;
  approverUserId: number;
  ledgerType: string;
  entryUserId: number | null;
  entryDate: Date;
  approversUserId: number | null;
  approvedDate: Date | null;
  isApproved: number;
  drAmount: number;
  crAmount: number;
  ledgersWaitingForApproval: number;
  partyName: string;
  purchaseOrderCode: string;
  entryUserName: string;
  supplierCostingHeadName: string;
}