name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-stage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t library-management-system -f ./DockerFile .

      # Step 5: Run Docker Compose
      - name: Run Docker Compose
        run: docker-compose up -d

      # Step 6: Check running containers
      - name: Check running containers
        run: docker ps -a

      # Step 7: View Docker Compose logs
      - name: View Docker Compose logs
        run: docker-compose logs

      # Step 8: Check API and frontend health
      - name: Test API health check
        run: |
          for i in {1..10}; do
            curl -f http://localhost:7070 && break || sleep 5
          done

      - name: Test Frontend health check
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8080 && break || sleep 5
          done

      # Step 9: Clean up
      - name: Stop and remove containers
        run: docker-compose down 

