name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-stage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t library-management-system -f ./DockerFile .
        
      # Step 3.5: Wait for the containers to start
      - name: Wait for containers
        run: sleep 30

      # Step 4: Run container to test
      - name: Run Docker container and test
        run: |
          docker run -d -p 7030:7030 -p 80:80 --name library-management-system library-management-system
          sleep 25 # Wait for the container to start

      # Step 5: Check API and frontend health
      - name: Test API health check
        run: |
          curl -f http://localhost:7030 || (echo "API is not running on port 7030" && exit 1)
      
      - name: Test Frontend health check
        run: |
          curl -f http://localhost || (echo "Frontend is not running on port 80" && exit 1)
      # Check container logs if health check fails
      - name: Check API container logs
        if: failure()
        run: docker logs library-management-system

      # Step 6: Clean up
      - name: Stop and remove container
        run: docker rm -f library-management-system
      
      
      #CHECK AGAIN
      
      # Step 4: Run container to test
      - name: Run Docker Compose
        run: docker-compose up -d
      
      # Step 5: Check API and frontend health
      - name: Test API health check
        run: |
          for i in {1..10}; do
            curl -f http://localhost:7070 && break || sleep 5
          done
      
      - name: Test Frontend health check
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8080 && break || sleep 5
          done
      
      # Step 6: Clean up
      - name: Stop and remove containers
        run: docker-compose down
