name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-stage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t library-management-system -f ./DockerFile .

      # Step 4: Use Docker Compose
      - name: Run Docker Compose
        uses: docker/compose-action@v2
        with:
          args: up -d

      # Step 5: Check API and frontend health
      - name: Test API health check
        run: |
          for i in {1..10}; do
            curl -f http://localhost:7070 && break || sleep 5
          done

      - name: Test Frontend health check
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8080 && break || sleep 5
          done

      # Add a step to view logs
      - name: View API container logs
        run: docker logs library-management-system

      # Step 6: Clean up
      - name: Stop and remove containers
        run: docker-compose down
