name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-stage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t library-management-system -f ./DockerFile .

      # Step 4: Run container to test
      - name: Run Docker container and test
        run: |
          docker run -d -p 7030:7030 -p 80:80 --name library-management-system library-management-system
          sleep 10 # Wait for the container to start

      # Step 5: Check API and frontend health
      - name: Test API health check
        run: |
          curl -f http://localhost:7030 || (echo "API is not running on port 7030" && exit 1)
      
      - name: Test Frontend health check
        run: |
          curl -f http://localhost || (echo "Frontend is not running on port 80" && exit 1)

      # Step 6: Clean up
      - name: Stop and remove container
        run: docker rm -f library-management-system
